export type CollectionMediaType = "movie" | "tv";

export interface ContentCollection {
  mediaType: CollectionMediaType;
  slug: string;
  label: string;
  originCountries?: string[];
  genreId?: number;
}

const europeanCountries = [
  "AD",
  "AL",
  "AM",
  "AT",
  "AZ",
  "BA",
  "BE",
  "BG",
  "BY",
  "CH",
  "CY",
  "CZ",
  "DE",
  "DK",
  "EE",
  "ES",
  "FI",
  "FR",
  "GE",
  "GB",
  "GR",
  "HR",
  "HU",
  "IE",
  "IS",
  "IT",
  "LI",
  "LT",
  "LU",
  "LV",
  "MC",
  "MD",
  "ME",
  "MK",
  "MT",
  "NL",
  "NO",
  "PL",
  "PT",
  "RO",
  "RS",
  "RU",
  "SE",
  "SM",
  "SI",
  "SK",
  "TR",
  "UA",
  "VA",
];

const eastAsianCountries = ["CN", "HK", "JP", "KR", "MO", "TW"];
const africanCountries = [
  "AO",
  "BF",
  "BI",
  "BJ",
  "BW",
  "CD",
  "CF",
  "CG",
  "CI",
  "CM",
  "CV",
  "DJ",
  "DZ",
  "EG",
  "ER",
  "ET",
  "GA",
  "GH",
  "GM",
  "GN",
  "GQ",
  "GW",
  "KE",
  "KM",
  "LR",
  "LS",
  "LY",
  "MA",
  "MG",
  "ML",
  "MR",
  "MU",
  "MW",
  "MZ",
  "NA",
  "NE",
  "NG",
  "RW",
  "SC",
  "SD",
  "SN",
  "SO",
  "SS",
  "ST",
  "SZ",
  "TD",
  "TG",
  "TN",
  "TZ",
  "UG",
  "ZA",
  "ZM",
  "ZW",
];

export const contentCollections: ContentCollection[] = [
  { mediaType: "movie", slug: "us", label: "US Movies", originCountries: ["US"] },
  { mediaType: "movie", slug: "british", label: "British Cinema", originCountries: ["GB"] },
  { mediaType: "movie", slug: "european", label: "European Cinema", originCountries: europeanCountries },
  { mediaType: "movie", slug: "indian", label: "Indian Cinema", originCountries: ["IN"] },
  { mediaType: "movie", slug: "nigerian", label: "Nigerian Cinema", originCountries: ["NG"] },
  { mediaType: "movie", slug: "east-asian", label: "East Asian Cinema", originCountries: eastAsianCountries },
  { mediaType: "movie", slug: "animation", label: "Animation", genreId: 16 },
  { mediaType: "movie", slug: "anime", label: "Japanese Anime", originCountries: ["JP"], genreId: 16 },
  { mediaType: "tv", slug: "us", label: "US TV", originCountries: ["US"] },
  { mediaType: "tv", slug: "british", label: "British TV", originCountries: ["GB"] },
  { mediaType: "tv", slug: "european", label: "European TV", originCountries: europeanCountries },
  { mediaType: "tv", slug: "indian", label: "Indian TV", originCountries: ["IN"] },
  { mediaType: "tv", slug: "east-asian", label: "East Asian TV", originCountries: eastAsianCountries },
  { mediaType: "tv", slug: "african", label: "African TV", originCountries: africanCountries },
  { mediaType: "tv", slug: "animation", label: "Animation", genreId: 16 },
  { mediaType: "tv", slug: "anime", label: "Japanese Anime", originCountries: ["JP"], genreId: 16 },
];
